### ISSUE TITLE
dead

### ISSUE THREAD

**Issue by addy005** [Hrishi2861/Terabox-Downloader-Bot#1]
ғᴀɪʟᴇᴅ ᴛᴏ ᴘʀᴏᴄᴇss ʏᴏᴜʀ ʀᴇǫᴜᴇsᴛ.
ɪғ ʏᴏᴜʀ ғɪʟᴇ sɪᴢᴇ ɪs ᴍᴏʀᴇ ᴛʜᴀɴ 120ᴍʙ ɪᴛ ᴍɪɢʜᴛ ғᴀɪʟ ᴛᴏ ᴅᴏᴡɴʟᴏᴀᴅ.

**Comment by XaltriX** [comment]
same here

**Comment by RajbharSaheb** [comment]
Please solve it

**Comment by Hrishi2861** [comment]
It's not the Repo/Bot issue, it is perfect repo.
The main issue is of Api, some videos of 1gb+ are also downloadable but some less than 10mb are not downloadable. Api is not perfect and as I am not the owner of it, I can't do anything.
![Screenshot_2024-07-13-07-34-37-896_tw nekomimi nekogram-edit](https://github.com/user-attachments/assets/6ed9d36a-02f1-4796-b6ae-9c89d0627abe)

**Comment by whostolemycookie** [comment]
> It's not the Repo/Bot issue, it is perfect repo. The main issue is of Api, some videos of 1gb+ are also downloadable but some less than 10mb are not downloadable. Api is not perfect and as I am not the owner of it, I can't do anything. ![Screenshot_2024-07-13-07-34-37-896_tw nekomimi nekogram-edit](https://private-user-images.githubusercontent.com/98945367/348443314-6ed9d36a-02f1-4796-b6ae-9c89d0627abe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODY3NzAsIm5iZiI6MTcyNDA4NjQ3MCwicGF0aCI6Ii85ODk0NTM2Ny8zNDg0NDMzMTQtNmVkOWQzNmEtMDJmMS00Nzk2LWI2YWUtOWM4OWQwNjI3YWJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE2NTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MWYyOTE5OWY2ZDhhMTE1NjAwYzBkNmVkMTY1ZGU3NTkwYmM3M2ZlYTk2MmU1OTdiOTQ0YWUxNDI3NjAzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yhuPieFUOOXeilYxFoNneFhF1f0pe883sSB_nFm6c8s)

man i got the bot working but where do i find terabox links can u give me the channel
? Like where u got the screen shot video from pls im down bad 🤤

**Comment by Hrishi2861** [comment]
@whostolemycookie There are many!!
